# Topic 1: Introduction To Tensors

In [1]:
import torch
torch .__version__

'2.0.1+cu117'

## Creating a Scalar

torch.tensor is the function used in the creation of tensors in PyTorch. You can learn more about it in the documentation https://pytorch.org/docs/stable/tensors.html

Vectors and scalars are often denoted by lowercase letters while matrices and tensors are denoted by uppercase letters.

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Checking the dimension of scalar
scalar.ndim

0

In [4]:
# Converting the tensor to a Python integer (Only works with one element)
# item is a function or a method
scalar.item()

7

## Creating a Vector

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# Checking the dimension
vector.ndim

1

In [7]:
# Checking the shape of the vector
# shape shows the number of elements in a tensor
vector.shape

torch.Size([2])

## Creating a Matrix

In [8]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

## Creating a Tensor

A tensor is a n-dimensional array.

In [11]:
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

The shape means there is one dimensional of three by three elements

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TENSOR.ndim

3

## Creating Random Tensors

torch.rand() is used to create random tensors. You can specify the size as a parameter. Size is written as a tuple because it symbolizes the rows and columns (rows, columns).

torch.ones() and torch.zeros() are methods used to fill tensors with zeros and ones. This is good for masking.

Masking is when a tensor's values are replaced with zeros to notify the model not to learn them. 

In [14]:
RANDOM = torch.rand(size=(3, 4))
RANDOM

tensor([[0.6497, 0.8580, 0.0766, 0.6172],
        [0.7607, 0.9066, 0.5695, 0.9826],
        [0.2263, 0.9961, 0.9537, 0.4280]])

In [15]:
STAND = torch.rand(size=(3, 223, 223))
STAND

tensor([[[0.3216, 0.2121, 0.2163,  ..., 0.2237, 0.1782, 0.4507],
         [0.1111, 0.2966, 0.1969,  ..., 0.8426, 0.9250, 0.3212],
         [0.3136, 0.2387, 0.0877,  ..., 0.6949, 0.9687, 0.1513],
         ...,
         [0.0798, 0.3703, 0.8754,  ..., 0.2705, 0.8092, 0.4108],
         [0.7301, 0.4897, 0.0030,  ..., 0.0612, 0.7000, 0.9767],
         [0.7657, 0.7396, 0.3934,  ..., 0.5955, 0.8367, 0.9716]],

        [[0.2654, 0.4546, 0.0310,  ..., 0.2153, 0.3266, 0.7308],
         [0.0017, 0.0134, 0.1484,  ..., 0.4998, 0.6531, 0.7750],
         [0.2480, 0.4790, 0.6489,  ..., 0.9042, 0.1309, 0.5194],
         ...,
         [0.1423, 0.8163, 0.8785,  ..., 0.0219, 0.9874, 0.3474],
         [0.4640, 0.5815, 0.3411,  ..., 0.4136, 0.3277, 0.0790],
         [0.6543, 0.4354, 0.3533,  ..., 0.7060, 0.9629, 0.7214]],

        [[0.5881, 0.8875, 0.7077,  ..., 0.8113, 0.7504, 0.3704],
         [0.8278, 0.4946, 0.0532,  ..., 0.3186, 0.6642, 0.2147],
         [0.6133, 0.7113, 0.3527,  ..., 0.8832, 0.2831, 0.

In [16]:
STAND.shape, STAND.ndim

(torch.Size([3, 223, 223]), 3)

In [17]:
ZERO = torch.zeros(size=(4, 2))
ZERO

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [18]:
ONES = torch.ones(size=(4, 3))
ONES

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.ones_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [23]:
x = torch.empty(2,2,2,3)
x.dtype

torch.float32

# Topic 2: Basic Operations on Tensors

* Operations on tensors are all element-wise

In [32]:
# Addition
Ten = torch.rand(2,2,3, dtype=torch.float32)
Sor = torch.rand(2,2,3, dtype=torch.float32)
Tensor = torch.add(ten,sor)
Tensor

tensor([[[0.8009, 1.1946, 0.7258],
         [1.1301, 1.2208, 1.3622]],

        [[1.2694, 0.3696, 1.7246],
         [1.0462, 1.8052, 1.4508]]])

In [48]:
# Mutiplication
Mel = torch.rand(3,3,3, dtype=torch.float32)
Mwe = torch.rand(3,3,3, dtype=torch.float32)
Mult = torch.mul(Mel,Mwe)
Mult

tensor([[[0.6786, 0.1423, 0.6290],
         [0.4964, 0.7624, 0.0119],
         [0.1521, 0.1442, 0.5613]],

        [[0.2348, 0.2067, 0.2392],
         [0.0689, 0.2006, 0.1829],
         [0.0074, 0.2074, 0.3263]],

        [[0.3542, 0.0159, 0.4318],
         [0.1463, 0.0704, 0.1685],
         [0.2402, 0.0083, 0.4392]]])

## Matrix Multiplication
*torch.matmul()* function is used to perform matrix multiplication. 

Rules to remember:
1. *The resulting matrix takes the shape of the outer dimensions.*
2. *The column of the first matrix should be equal to the row of the second matrix and vice versa.*

In [50]:
# Matrix Multiplication
Mat = torch.rand(4,5)
Mul = torch.rand(5,6)
Result = torch.matmul(Mat, Mul)
Result

tensor([[1.3205, 1.8921, 1.7919, 1.8462, 1.0696, 1.2850],
        [1.2865, 1.5576, 1.7718, 1.6191, 0.9376, 0.9178],
        [1.4454, 1.9737, 1.9005, 2.1615, 1.1239, 1.2105],
        [0.4989, 0.7466, 0.8298, 0.7934, 0.4306, 0.4667]])

Difference between matrix multiplication and element-wise multiplication is in the addition.

Element-wise multiplication	  [1 * 1, 2 * 2, 3 * 3] = [1, 4, 9]	      tensor * tensor

Matrix multiplication	      [1 * 1 + 2 * 2 + 3 * 3] = [14]	       tensor.matmul(tensor)

# Common Errors Performed in Deep Learning

* These are some of the most common errors performed during matrix multiplication that is a common operation in deep learning.

## 1. Shape Mismatches

In [53]:
TensorA = torch.rand(2,3)
TensorB = torch.rand(2,3)
Result = torch.matmul(TensorA, TensorB)
Result

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

For this error to be solved, transpose should be performed. Transpose is when the dimension of a matrix is switched. In this case, **TensorB** should have a shape of (3,2). 

There are two methods in which transpose can be performed in Pytorch:

*i)Using **torch.transpose(input,dim0,dim1)** where input is the desiired tensor to be transposed while dim0 and dim1 are the needed dimensions to be swapped.*

*ii)Using tensor.T where **tensor** is the desired tensor to be transposed.*

In [56]:
# Print TensorA and TensorB
print('TensorA: ', TensorA)
print('Shape of TensorA: ', TensorA.shape)
print('TensorB: ', TensorB)
print('Shape of TensorB: ', TensorB.shape)

TensorA:  tensor([[0.1727, 0.3120, 0.4230],
        [0.8137, 0.6415, 0.4276]])
Shape of TensorA:  torch.Size([2, 3])
TensorB:  tensor([[0.5013, 0.4516, 0.8435],
        [0.7912, 0.3250, 0.4745]])
Shape of TensorB:  torch.Size([2, 3])


Using the rules on matrix multiplication given above, the shape of the tensors are mismatched hence transpose needs to be performed.

In [66]:
# Performing Transpose on TensorB using method i
New_TensorB = torch.transpose(TensorB, 0, 1)
print('Transposed TensorB: ',New_TensorB)
print('Shape of transposed TensorB: ',New_TensorB.shape)

Transposed TensorB:  tensor([[0.5013, 0.7912],
        [0.4516, 0.3250],
        [0.8435, 0.4745]])
Shape of transposed TensorB:  torch.Size([3, 2])


In [67]:
# Performing Transpose on TensorB using method ii
New_TensorB = TensorB.T
print('Transposed TensorB: ',New_TensorB)
print('Shape of transposed TensorB: ',New_TensorB.shape)

Transposed TensorB:  tensor([[0.5013, 0.7912],
        [0.4516, 0.3250],
        [0.8435, 0.4745]])
Shape of transposed TensorB:  torch.Size([3, 2])


In [70]:
# Performing Matrix Multiplication on the tensors
print('Shape of TensorA: ', TensorA.shape)
print('Shape of New_TensorB: ', New_TensorB.shape)
TensorAB = torch.matmul(TensorA, New_TensorB)
print('TensorAB: ', TensorAB)
print('Shape of TensorAB: ', TensorAB.shape)

Shape of TensorA:  torch.Size([2, 3])
Shape of New_TensorB:  torch.Size([3, 2])
TensorAB:  tensor([[0.5843, 0.4387],
        [1.0582, 1.0551]])
Shape of TensorAB:  torch.Size([2, 2])
