# Topic 1: Introduction To Tensors

In [2]:
import torch
torch .__version__

'2.0.1+cu117'

## Creating a Scalar

torch.tensor is the function used in the creation of tensors in PyTorch. You can learn more about it in the documentation https://pytorch.org/docs/stable/tensors.html

Vectors and scalars are often denoted by lowercase letters while matrices and tensors are denoted by uppercase letters.

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# Checking the dimension of scalar
scalar.ndim

0

In [5]:
# Converting the tensor to a Python integer (Only works with one element)
# item is a function or a method
scalar.item()

7

## Creating a Vector

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
# Checking the dimension
vector.ndim

1

In [8]:
# Checking the shape of the vector
# shape shows the number of elements in a tensor
vector.shape

torch.Size([2])

## Creating a Matrix

In [9]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

## Creating a Tensor

A tensor is a n-dimensional array.

In [12]:
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

The shape means there is one dimensional of three by three elements

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR.ndim

3

## Creating Random Tensors

torch.rand() is used to create random tensors. You can specify the size as a parameter. Size is written as a tuple because it symbolizes the rows and columns (rows, columns).

torch.ones() and torch.zeros() are methods used to fill tensors with zeros and ones. This is good for masking.

Masking is when a tensor's values are replaced with zeros to notify the model not to learn them. 

In [15]:
RANDOM = torch.rand(size=(3, 4))
RANDOM

tensor([[0.5044, 0.8057, 0.9673, 0.1332],
        [0.8191, 0.3806, 0.9817, 0.8691],
        [0.1380, 0.1628, 0.3777, 0.4565]])

In [19]:
STAND = torch.rand(size=(3, 223, 223))
STAND

tensor([[[2.6796e-02, 6.1009e-01, 7.6544e-03,  ..., 4.1531e-01,
          7.6767e-01, 4.8885e-01],
         [7.4805e-01, 4.1287e-01, 9.8839e-01,  ..., 6.0375e-01,
          3.9755e-01, 6.4545e-02],
         [2.6468e-01, 2.0426e-01, 3.5580e-01,  ..., 2.9325e-01,
          4.1832e-01, 2.3925e-01],
         ...,
         [1.0844e-01, 1.5335e-01, 7.9927e-01,  ..., 1.2639e-01,
          1.8240e-01, 2.2481e-01],
         [2.9480e-01, 1.3731e-01, 7.3585e-01,  ..., 2.3564e-01,
          4.7504e-01, 7.7331e-01],
         [7.6894e-01, 4.2582e-01, 7.0976e-02,  ..., 8.2059e-01,
          3.3315e-01, 1.0736e-01]],

        [[7.1840e-01, 5.6666e-01, 4.1429e-01,  ..., 4.3696e-01,
          2.3610e-01, 2.9723e-01],
         [9.8230e-01, 3.2228e-01, 2.7119e-01,  ..., 1.0231e-01,
          5.5619e-01, 6.8053e-01],
         [2.0600e-01, 9.9451e-01, 8.0454e-01,  ..., 5.2865e-01,
          9.9120e-02, 7.0473e-01],
         ...,
         [9.0952e-01, 9.7725e-01, 4.1225e-01,  ..., 5.9238e-01,
          1.142

In [20]:
STAND.shape, STAND.ndim

(torch.Size([3, 223, 223]), 3)

In [16]:
ZERO = torch.zeros(size=(4, 2))
ZERO

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [18]:
ONES = torch.ones(size=(4, 3))
ONES

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [23]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])